services:
  backend:
    build: ./backend
    container_name: the-office-backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - office-network

  frontend:
    build: ./frontend-react
    container_name: the-office-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - office-network

networks:
  office-network:
    driver: bridge

volumes:
  backend_data:
